"""Document added

Revision ID: 2ef5a832df33
Revises: 499c57dcd449
Create Date: 2024-04-27 14:07:19.665405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef5a832df33'
down_revision = '499c57dcd449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default='2024-02-13 11:11:11.391181-07', nullable=False),
    sa.Column('full_text', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('effective_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('price_escalator', sa.Float(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('billing_contact', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_filename'))

    op.drop_table('document')
    # ### end Alembic commands ###
