"""starting db again


Revision ID: 35ee55201b0f
Revises: 
Create Date: 2024-04-27 15:22:45.695101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ee55201b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), server_default='Firstname', nullable=False),
    sa.Column('lastname', sa.String(length=64), server_default='Lastname', nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('first_seen', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_seen', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_message_read_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('organization', sa.String(length=64), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default='2024-02-13 11:11:11.391181-07', nullable=False),
    sa.Column('full_text', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('effective_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('price_escalator', sa.Float(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('billing_contact', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_filename'))

    op.drop_table('document')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
